version: '3'

services:
  database:
    image: mariadb
    restart: always
    container_name: airtradex_protect_database
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - /home/sergey/data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
