version: '3'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - airtradex:/var/lib/mysql/data
    ports:
      - "3306:3306"
    networks:
      - airtradex

volumes:
  airtradex:

networks:
  airtradex: