version: '3'

services:
  database:
    image: mariadb
    restart: always
    container_name: airtradex_protect_database
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./init.sql:/data/application/init.sql
      - /home/sergey/data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql

  protector:
    image: airtradex_protect
    restart: always
    ports:
      - 8000:8000
    links:
      - database
