version: '3'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./init.sql:/data/application/init.sql
      - /home/sergey/mysql-data:/var/lib/mysql
    ports:
      - 33060:3306
    command: --init-file /data/application/init.sql

  onlinestore:
    build: .
    image: drcoyote/online-store:1.0
    restart: always
    ports:
      - 7890:8000
    links:
      - database
    depends_on:
      - database
    environment:
      DB_HOST: "database"
      DB_PASSWORD: 12345

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - database:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    depends_on:
      - database
